server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ec2-52-30-159-47.eu-west-1.compute.amazonaws.com:5432/dfj0673qhs69e2
    username: MAIL TO ME !!
    password: DO U WANNA SEE MY PASSWORDS ? MAIL TO ME !! :P
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    user:
#      name: admin
#      password: admin